version: '3.6'
services:
  backend:
    build:
      context: .
      target: development
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - /usr/src/app/node_modules/
      - .:/usr/src/app
    depends_on:
      - postgresdev
    command: ["yarn", "run", "dev"]
  postgresdev:
    image: postgres:10.4
    environment:
      - POSTGRES_USER=postgresdev
      - POSTGRES_PASSWORD=postgresdev
      - POSTGRES_DB=fakeroku
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - fakeroku-postgresdev:/var/lib/postgresql/data/pgdata
volumes:
  fakeroku-postgresdev:
